package utils

class MimeTypeUtils {

    static final public String MIMETYPE_TIFF = "image/tiff"
    static final public String MIMETYPE_JPEG = "image/jpeg"
    static final public String MIMETYPE_GIF = "image/gif"
    static final public String MIMETYPE_PNG = "image/png"
    static final public String MIMETYPE_ZIP = "application/zip"
    static final public String MIMETYPE_BMP = "image/bmp"
    static final public String MIMETYPE_PBM = "image/x-portable-bitmap"
    static final public String MIMETYPE_PNM = "image/x-portable-anymap"
    static final public String MIMETYPE_PPM = "image/x-portable-pixmap"
    static final public String MIMETYPE_VSI = "olympus/vsi"
    static final public String MIMETYPE_DOTSLIDE = "olympus/.slide"
    static final public String MIMETYPE_OMETIFF = "ome/ome-tiff"
    static final public String MIMETYPE_ZEISSCZI = "zeiss/czi"
    static final public String MIMETYPE_SVS = "openslide/svs"
    static final public String MIMETYPE_NDPI = "openslide/ndpi"
    static final public String MIMETYPE_VMS = "openslide/vms"
    static final public String MIMETYPE_SCN = "openslide/scn"
    static final public String MIMETYPE_MRXS = "openslide/mrxs"
    static final public String MIMETYPE_PTIFF = "philips/tif"
    static final public String MIMETYPE_SAKURA = "sakura/svslide"
    static final public String MIMETYPE_BIF = "openslide/bif"
    static final public String MIMETYPE_VTIFF = "openslide/ventana"
    static final public String MIMETYPE_JP2 = "image/jp2"
    static final public String MIMETYPE_PYRTIFF = "image/pyrtiff"
    static final public String MIMETYPE_DICOM = "application/dicom"
}
